[package]
name = "mcts"
version = "0.1.0"
edition = "2021"

[dependencies]
tilers-core = { path = "/Users/mathias/Documents/research/tilers/tilers-core" }
dashmap = "6"
rand = "0.9"
crossbeam = "0.8"
serde = { version = "1", features = ["derive"] }
bincode = { version = "2.0", features = ["serde"] }
thiserror = "2.0"
itertools = "0.14"