[package]
name = "pymcts"
version = "0.1.0"
edition = "2024"

[lib]
name = "pymcts"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.2", features = ["extension-module"] }
numpy = "0.27"
anyhow = "1"

tilers-core = { path = "/Users/mathias/Documents/research/tilers/tilers-core" }
mcts-core = { path = "../mcts-core" }
