from __future__ import annotations

from typing import Any

class MctsEnvironment:
    def __init__(self, obj: Any) -> None: ...
    def step(self, action: int) -> None: ...
    def done(self) -> bool: ...
    def observation(self) -> Any: ...
    def valid_actions(self) -> list[int]: ...
    def hash_state(self) -> int: ...
    def render(self) -> str: ...

class MctsAgent:
    def __init__(self, obj: Any) -> None: ...
    def infer(self, obs: list[Any]) -> tuple[list[dict[int, float]], list[float]]: ...

class MctsNode:
    def id(self) -> int: ...
    def prior_probs(self) -> dict[int, float]: ...
    def value(self) -> float: ...
    def terminal_state(self) -> bool: ...
    def repr(self) -> str | None: ...
    def edge_visits(self) -> dict[int, int]: ...

class PyMcts:
    def __init__(self, terminal_value: float = 1.0, batch_size: int = 8) -> None: ...
    def run(self, env: MctsEnvironment, agent: MctsAgent, num_steps: int) -> MctsNode: ...