from __future__ import annotations

import numpy as np
from numpy.typing import NDArray

MAX_BATCH: int
GRID_MAX: int
MAX_OBJ0: int
MAX_OBJ1: int
NUM_ACTIONS: int

class PyArena:
    def __init__(self, name: str, num_slots: int, num_handlers: int) -> None: ...
    def num_slots(self) -> int: ...
    def pop_ready(self, handler: int) -> int: ...
    def mark_done(self, slot: int) -> None: ...
    def clear_outputs(self, slot: int) -> None: ...
    def pop_ready_view(self, handler: int, clear_outputs: bool = False) -> PySlotView: ...
    def try_pop_ready_view(self, handler: int, clear_outputs: bool = False) -> PySlotView | None: ...

class PySlotView:
    slot: int
    def b(self) -> int: ...
    def h(self) -> NDArray[np.uint8]: ...
    def w(self) -> NDArray[np.uint8]: ...
    def num_ancillas(self) -> NDArray[np.uint8]: ...
    def obj0_len(self) -> NDArray[np.uint16]: ...
    def obj1_len(self) -> NDArray[np.uint16]: ...
    def placement(self) -> NDArray[np.uint16]: ...      # shape (b, GRID_MAX)
    def obj0(self) -> NDArray[np.uint16]: ...
    def obj1(self) -> NDArray[np.uint16]: ...
    def action_mask(self) -> NDArray[np.uint8]: ...    # shape (b, NUM_ACTIONS)
    def priors(self) -> NDArray[np.float32]: ...       # shape (b, NUM_ACTIONS)
    def values(self) -> NDArray[np.float32]: ...       # shape (b,)
    def mark_done(self) -> None: ...