from __future__ import annotations
from typing import Any

# ------------------------------------------------------------------------------
# Constants (exported from Rust)
# ------------------------------------------------------------------------------
QUBIT_SIZE: int
OBJECTIVE_SIZE: int
PLACEMENT_MAX: int
OBJECTIVES_LAYER_MAX: int
OBJECTIVES_MAX: int
LOOKAHEAD_MAX: int
GRID_MAX: int
NUM_ACTIONS: int

# ------------------------------------------------------------------------------
# Arena + SlotView (IPC layer)
# ------------------------------------------------------------------------------
class PySlotView:
    slot: int

    def arena_name(self) -> str: ...
    def num_slots(self) -> int: ...
    def b(self) -> int: ...
    def placement(self) -> memoryview: ...
    def objectives(self) -> memoryview: ...
    def action_mask(self) -> memoryview: ...
    def h(self) -> memoryview: ...
    def w(self) -> memoryview: ...
    def num_ancillas(self) -> memoryview: ...
    def num_qubits(self) -> memoryview: ...
    def num_layers(self) -> memoryview: ...
    def num_objectives(self) -> memoryview: ...
    def last_dir_vertical(self) -> memoryview: ...
    def write_priors_values(
        self, priors: Any, values: Any,
    ) -> None: ...
    def set_handler_start_time(self) -> None: ...
    def mark_done(self) -> None: ...

class PyArena:
    def __init__(
        self, name: str, num_slots: int, num_handlers: int,
    ) -> None: ...
    def pop_ready_view(
        self, *, handler: int, clear_outputs: bool = True,
    ) -> PySlotView: ...
    def try_pop_ready_view(
        self, *, handler: int, clear_outputs: bool = True,
    ) -> PySlotView | None: ...
    def force_reset(self) -> None: ...
    def submit_and_collect(
        self,
        h: int,
        w: int,
        num_blanks: int,
        num_objectives: int,
        seed: int,
    ) -> tuple[list[list[float]], list[float]]: ...

# ------------------------------------------------------------------------------
# MCTS types
# ------------------------------------------------------------------------------
class MctsEnvironment:
    def observe(self) -> Any: ...
    def valid_actions(self) -> list[int]: ...
    def step(self, action: int) -> tuple[float, bool]: ...
    def clone(self) -> MctsEnvironment: ...

class MctsAgent:
    def __init__(self, obj: Any) -> None: ...
    def infer(
        self, obs: list[Any],
    ) -> tuple[list[dict[int, float]], list[float]]: ...

class MctsNode:
    def id(self) -> int: ...
    def prior_probs(self) -> dict[int, float]: ...
    def value(self) -> float: ...
    def terminal_state(self) -> bool: ...
    def repr(self) -> str | None: ...
    def edge_visits(self) -> dict[int, int]: ...

class PyMcts:
    def __init__(
        self, terminal_value: float = 1.0, batch_size: int = 8,
    ) -> None: ...
    def run(
        self,
        env: MctsEnvironment,
        agent: MctsAgent,
        num_steps: int,
    ) -> MctsNode: ...
    def advance_root(self, action: int) -> None: ...
